---
server:
  port: 8201

spring:
  profiles: dev
  application:
    name: microservicecloud-config-client-8021

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/

---
server:
  port: 8202

spring:
  profiles: test
  application:
    name: microservicecloud-config-client-8202

eureka:
  client:
    service-url:
      defaultZone: http://eureka7002:7002/eureka/
